config/routes.rb
Rails.application.routes.draw do
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:create]
  end
  resources :doses, only: [:destroy]
  root to: "cocktails#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true

  mount_uploader :photo, PhotoUploader

  def list_ingredients
    ingredients.map(&:name).join(', ')
  end
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, presence: true, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show]

  def index
    @cocktails = Cocktail.all
    @cocktail = Cocktail.new
  end

  def show
    @dose = Dose.new
  end

  def new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail, notice: 'Cocktail was successfully created.'
    else
      render :new, notice: 'Input invalid. Please try again'
    end
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_dose, only: [:destroy]
  before_action :set_cocktail, only: [:new, :create]

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def destroy
    @dose.destroy
    @cocktail = @dose.cocktail
    redirect_to @cocktail
  end

  private

  def set_dose
    @dose = Dose.find(params[:id])
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-success' %>
  </div>
<% end %>

app/views/cocktails/index.html.erb
<%= render 'shared/banner' %>
<div class="container">
  <h1>Cocktails</h1>
  <div class="row">
    <% @cocktails.each do |cocktail| %>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url('<%= cl_image_path cocktail.photo %>');">
        <div class="card-description">
          <h2><%= cocktail.name %></h2>
          <p><%= cocktail.list_ingredients %></p>
        </div>
        <%= link_to "", cocktail, class:"card-link" %>
      </div>
    </div>
    <% end %>
    <div class="col-xs-12 col-sm-6 col-md-4">
    <div class="card card-new" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url('https://image.flaticon.com/icons/png/512/32/32360.png');">
        <div class="card-description">
        </div>
        <%= link_to "", "#", data: { toggle: "modal", target: "#addCocktail"}, class:"card-link" %>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <h1>Add new Cocktail</h1>
  <div class="row">
    <div class="col-lg-12">
      <p><%= render 'form', cocktail: @cocktail %></p>
      <p><%= link_to 'Go Back', cocktails_path, class:"btn btn-primary" %></p>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="cocktail-banner" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url('<%= cl_image_path @cocktail.photo %>');">
  <div class="banner-content">
    <h1><%= @cocktail.name %></h1>
  </div>
</div>
<div class="container">
  <div class="cocktail-box">
    <% @cocktail.doses.each do |dose| %>
    <div class="details-box">
      <div class="items-first">
        <%= dose.ingredient.name %>
      </div>
      <div class="items-middle">
        <%= dose.description %>
      </div>
      <div class="items-last">
        <%= link_to dose_path(dose),
        method: :delete,
        data: { confirm: "Are you sure?" } do %>
          <i class="far fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
  <div class="new-ingredient">
    <%= render '/doses/form' %>
  </div>
</div>

app/views/doses/_form.html.erb
<%= simple_form_for [@cocktail, @dose], html: { class: 'form-inline' } do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <%= f.association :ingredient, label: false, prompt: "New ingredient" %>
  <%= f.input :description, label: false, placeholder: "Amount" %>
  <%= f.button :button do %>
    <i class="fas fa-plus"></i>
  <% end %>
<% end %>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/new.html.erb
<h1>Doses#new</h1>
<p>Find me in app/views/doses/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <% if controller_name == 'cocktails' && action_name == "index" %>
      <%= render "shared/transparent-navbar" %>
    <% else %>
      <%= render "shared/navbar" %>
    <% end %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag "application" %>

    <%= render 'shared/modal' %>
  </body>
</html>

app/views/shared/_banner.html.erb
<div class="home-banner">
  <div class="banner-content">
    <h1>The Lord of Cocktails</h1>
    <p>
      <span id="banner-typed-text"></span>
    </p>
  </div>
</div>

app/views/shared/_modal.html.erb
<div class="modal fade" id="addCocktail" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="addCocktailLabel">Add Cocktail</h4>
      </div>
      <div class="modal-body">
        <%= render "cocktails/form" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-white">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>
  <h1>The Lord of Cocktails</h1>

    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <i class="fas fa-bars" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "Cocktails", cocktails_path %>
          </li>
          <li>
            <%= link_to "Add a Cocktail", "#", data: { toggle: "modal", target: "#addCocktail"} %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_transparent-navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <i class="fas fa-bars" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "Cocktails", cocktails_path %>
          </li>
          <li>
            <%= link_to "Add a Cocktail", "#", data: { toggle: "modal", target: "#addCocktail"} %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>